#!/bin/bash

(make clean; make) || exit 1

source ../../tester/testall

runtest mytest "test1" none 1 5
runtest mytest "test2" none 1 5
runtest mytest "test3" none 1 5
runtest mytest "test4" none 1 5

printResults
